/********************************************************************
* ftttestDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error ftttestDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableftttestDict();
extern void G__cpp_setup_inheritanceftttestDict();
extern void G__cpp_setup_typetableftttestDict();
extern void G__cpp_setup_memvarftttestDict();
extern void G__cpp_setup_globalftttestDict();
extern void G__cpp_setup_memfuncftttestDict();
extern void G__cpp_setup_funcftttestDict();
extern void G__set_cpp_environmentftttestDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ftttest.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__ftttestDictLN_TClass;
extern G__linked_taginfo G__ftttestDictLN_TBuffer;
extern G__linked_taginfo G__ftttestDictLN_TMemberInspector;
extern G__linked_taginfo G__ftttestDictLN_TObject;
extern G__linked_taginfo G__ftttestDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__ftttestDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ftttestDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__ftttestDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__ftttestDictLN_input_sample;
extern G__linked_taginfo G__ftttestDictLN_solve_data;

/* STUB derived class for protected member access */
