/********************************************************************
* patternDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error patternDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablepatternDict();
extern void G__cpp_setup_inheritancepatternDict();
extern void G__cpp_setup_typetablepatternDict();
extern void G__cpp_setup_memvarpatternDict();
extern void G__cpp_setup_globalpatternDict();
extern void G__cpp_setup_memfuncpatternDict();
extern void G__cpp_setup_funcpatternDict();
extern void G__set_cpp_environmentpatternDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "pattern.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__patternDictLN_TClass;
extern G__linked_taginfo G__patternDictLN_TBuffer;
extern G__linked_taginfo G__patternDictLN_TMemberInspector;
extern G__linked_taginfo G__patternDictLN_TObject;
extern G__linked_taginfo G__patternDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__patternDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__patternDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__patternDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__patternDictLN_input_sample;
extern G__linked_taginfo G__patternDictLN_solve_data;

/* STUB derived class for protected member access */
